import type { Metadata } from 'next';
import { Roboto_Mono } from 'next/font/google';
import './globals.css';
import { Header } from '@/lib/components/layout/Header';
import { Footer } from '@/lib/components/layout/Footer';

const robotoFont = Roboto_Mono({
    weight: '400',
    subsets: ['cyrillic'],
});

export const metadata: Metadata = {
    title: 'киношки',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body
                className={`${robotoFont.className} antialiased w-full h-screen flex flex-col`}
            >
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
