name: Deploy Next.js site to GitHub Pages

on:
    workflow_dispatch:

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'
                  cache: 'npm'

            - name: Setup Pages
              uses: actions/configure-pages@v5
              with:
                  # Automatically inject basePath in your Next.js configuration file and disable
                  # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
                  static_site_generator: next

            - name: Install dependencies
              run: npm ci

            - name: Build with Next.js
              env:
                  NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
                  NEXT_PUBLIC_API_KEY: ${{ secrets.NEXT_PUBLIC_API_KEY }}
              run: npm run pages

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out
                  publish_branch: gh-pages
